### ISSUE TITLE
how do we change the dim.js values dynamically , suppose i want to call a api and resulting colors , i want to pass it to the export so the latest are reflecting

### ISSUE THREAD

**Issue by deepika-Gopala** [tompascall/js-to-styles-var-loader#5]
Hi seems like i can use this to theme the application , can anyone help how i can change the module.export dynamically based on api response in dims.js

**Comment by tompascall** [comment]
Hi! It seems to me that your question is not an issue of the loader. Would you like to build your less files depending on a server response?
